### ISSUE TITLE
Activating plugin breaks Craft

### ISSUE THREAD

**Issue by 23d1** [imarc/craft-sass#3]
Hoping this might be a user error. When I install/activate the plugin the site goes down, to which point I need to go into the database and uninstall it that way.

Any ideas?

Using the latest Craft 2.6 version.

**Comment by chasegiunta** [comment]
Confirming, same.

**Comment by jeffturcotte** [comment]
Thanks for the reports. We are looking into this.

**Comment by khamer** [comment]
I suspect this is because we changed how it's installed to fit better with composer/installers.

The new installation method should be
1. In the **root** of your project, run `composer require imarc/craft-sass`.This will create a `vendor/` directory as well as automatically put the plugin it self in `craft/plugins/sass/`.
2. Upload both the `vendor/` and `craft/plugins/sass/` directories.
3. Enable the plugin in the Craft Plugins panel.

This replaces the existing installation steps. Let me know if this works for you.

**Comment by khamer** [comment]
Closing this issue, as I believe this did fix the issue and didn't hear either way.
