### ISSUE TITLE
Doesn't import when compiling

### ISSUE THREAD

**Issue by 23d1** [imarc/craft-sass#5]
It doesn't seem to import the @import scss-files.

**Comment by tannerevans** [comment]
Confirming, same.

**Comment by jeffturcotte** [comment]
Can you please supply some more information? In my tests, it appears that the @import works.

What does your scss directory structure look like? By default, the leafo scss compiler's import path is the same as your root scss file. http://leafo.net/scssphp/docs/#import_paths

Thanks.

**Comment by tannerevans** [comment]
Tested very simply by making a styles.scss file that does 2 nested styles (to test that it's actually compiling), which works. Then has an @import 'testImport'; to another file named "_testImport.scss" (within same directory) that only has one simple style in it. This is not being imported into the compiled css.

Calling compiled css in head: <link href="{{ craft.sass.link('/assets/css/sass/styles.scss') }}">

What renders is the following:

/\* compiled by scssphp v0.1.10 on Thu, 19 May 2016 19:18:22 +0000 (0.0012s) */

@import 'testImport';
body {
  background-color: #e60; }
  body header {
    background-color: #6e0; }

**Comment by davidgeere** [comment]
Exact same here

**Comment by khamer** [comment]
The bug here is that craft-sass ignores the path of the original file included and assumes imports are relative to document root. So, if you use `{{ craft.sass.link('/css/styles.scss') }}` as your entry point, to include /css/_components.scss you have to `@import 'css/components';`.

We may be able to fix this, but we are shifting towards using laravel mix on new projects and away from server-side sass compilation. In the mean time, try that workaround.
